org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
loader_version_range=[1,)


mod_id=precisionprospecting
mod_name=Precision Prospecting
mod_license=EUPLv1.2
mod_version=2.0
mod_group_id=io.github.notenoughmail.precisionprospecting
mod_authors=NotEnoughMail
mod_description=Adding new prospecting tools

tfc_file=8666972
patchi_file=6842247
jei_file=6829086
jei_version=19.25.0.322

tfc_min_version=4.2.8
